# Generated by Django 4.0.6 on 2022-07-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('surname', models.CharField(max_length=100, verbose_name='Familyasi')),
                ('age', models.PositiveIntegerField(verbose_name='Yoshi')),
                ('gender', models.IntegerField(choices=[(1, 'Male (Erkak)'), (2, 'Female (Ayol)')], verbose_name='Jinsi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
