# Generated by Django 4.0.5 on 2022-07-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='token',
            field=models.CharField(default='0d58fb625b50e9745bafd5243f0fce98', max_length=500),
        ),
    ]
