# Generated by Django 4.0.6 on 2022-07-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_custom_user_age_alter_custom_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='token',
            field=models.CharField(default='f55a0a3d8019c00b7eb5bdcbe4af4cac', max_length=500),
        ),
    ]
