# Generated by Django 4.0.6 on 2022-07-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_custom_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='token',
            field=models.CharField(default='3a2f805401a41ede33395bd83fae6db2', max_length=500),
        ),
    ]
