# Generated by Django 4.0.6 on 2022-07-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_custom_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Yoshi'),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male (Erkak)'), (2, 'Female (Ayol)')], verbose_name='Jinsi'),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Familyasi'),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='token',
            field=models.CharField(default='0b2109d75ade84fdea115c607639f59f', max_length=500),
        ),
    ]
