# Generated by Django 4.0.6 on 2022-07-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_custom_user_age_alter_custom_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='token',
            field=models.CharField(default='9b41b2cd4be5b180bd2416bce0add601', max_length=500),
        ),
    ]
